-- Audit tables for usage statistics (PostgreSQL 14+)
-- If using ldap-login-architecture-skill, these tables already exist.

CREATE TABLE IF NOT EXISTS auth_login_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  request_id TEXT,
  user_id TEXT NULL,
  username_input TEXT NOT NULL,
  success BOOLEAN NOT NULL,
  failure_code TEXT NULL,
  source_ip TEXT NULL,
  user_agent TEXT NULL,
  department_snapshot TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_login_events_occurred_at
  ON auth_login_events (occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_login_events_user_time
  ON auth_login_events (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_login_events_success_time
  ON auth_login_events (success, occurred_at DESC);

CREATE TABLE IF NOT EXISTS auth_session_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  session_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('created', 'accessed', 'refreshed', 'revoked', 'expired', 'logout')),
  reason TEXT NULL,
  source_ip TEXT NULL,
  user_agent TEXT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_session_events_user_time
  ON auth_session_events (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_session_events_type_time
  ON auth_session_events (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_session_events_session_time
  ON auth_session_events (session_id, occurred_at DESC);
